### ISSUE TITLE
build script failing on build.py

### ISSUE THREAD

**Issue by zhailei31665431** [atom/atom-shell-starter#93]
hey yo,

So I'm having some issues running the build script script/build on OSX 10.10.2.

Python version: 2.7.10 
Node version: 0.12.7

Everything seems to run correctly till this.

![image](https://cloud.githubusercontent.com/assets/3082395/9571008/acf390ba-4fc9-11e5-9060-28e8f2d3dc21.png)

How i need to do ?

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom-archive/electron-starter), this package is no longer maintained and is deprecated. We recommend that people use [electron-prebuilt](https://github.com/mafintosh/electron-prebuilt) and [electron-packager](https://github.com/maxogden/electron-packager) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
